version: "3.8"

services:
  mongo:
    image: mongo
    container_name: servicehub-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: servicehub-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # Interfaz web
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  backend-api:
    build:
      context: ./backend-api
    container_name: servicehub-backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/servicehub
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - mongo
      - rabbitmq

  notifications-service:
    build:
      context: ./notifications-service
    container_name: servicehub-notifier
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - rabbitmq

volumes:
  mongo_data:
